### PR TITLE
feat: also transform files with mjs extension

### PR DESCRIPTION
**Pull request by klipstein**

### CODE REVIEW

**Review by SukkaW — APPROVED** [review]

**Comment by SukkaW** [comment]
Merged, thanks! I will release a newer version ASAP.

**Comment by klipstein** [comment]
@SukkaW somehow this change did not get into latest release. Would be great if that would be part of the next release.

**Comment by SukkaW** [comment]
> @SukkaW somehow this change did not get into the latest release. Would be great if that would be part of the next release.

Yeah, I notice that, too.

I will add `mjs` extension support in the next version, with a better approach.

**Comment by klipstein** [comment]
Thanks for letting me know.

**Comment by klipstein** [comment]
@SukkaW I've seen that you pushed support for mjs here: https://github.com/SukkaW/rollup-plugin-swc/commit/c53a65cda4a4e2bbf08d13e0cdef36c8dc132c0c. Would be great if you could bump a new version including this change?

**Comment by SukkaW** [comment]
> @SukkaW I've seen that you pushed support for mjs here: [c53a65c](https://github.com/SukkaW/rollup-plugin-swc/commit/c53a65cda4a4e2bbf08d13e0cdef36c8dc132c0c). Would be great if you could bump a new version including this change?

I see the `\0` issue is being discussed and worked on (https://github.com/swc-project/swc/issues/2853, https://github.com/rollup/rollup/issues/4290) and thought maybe I can include the fix in the next version. Also, an swc contributor told me that the `\0` issue is likely caused by the rust lang itself. I will release a newer version if that is confirmed.

**Comment by klipstein** [comment]
I just don't understand what the \0 escape issue (where a fix is already published in version 0.1.3) is related to handling files with mjs extension. It also seems that the \0 escape cannot be fixed easily in Rust land. Would really like to use this plugin but my project depends on node dependencies that use .mjs files.

**Comment by SukkaW** [comment]
> I just don't understand what the \0 escape issue (where a fix is already published in version 0.1.3) is related to handling files with mjs extension. It also seems that the \0 escape cannot be fixed easily in Rust land. Would really like to use this plugin but my project depends on node dependencies that use .mjs files.

I'd like to include more changes in a version.

And a newer version 0.1.4 just released.

**Comment by klipstein** [comment]
Thanks for your help and bumping a new version.

**Pull request merged**
